"""Tests for mean_variance.py. These pass as provided. Do not edit this file."""

import numpy as np

from mean_variance import (
    efficient_weights,
    frontier,
    frontier_variance,
    max_sharpe_weights,
    minimize_variance,
)

MU = np.array([0.04, 0.08, 0.12])
SIGMA = np.array(
    [
        [0.04, 0.01, 0.00],
        [0.01, 0.09, 0.02],
        [0.00, 0.02, 0.16],
    ]
)
RF = 0.02


def test_closed_form_weights_satisfy_the_constraints():
    w = efficient_weights(MU, SIGMA, target=0.10)
    assert np.isclose(w.sum(), 1)
    assert np.isclose(w @ MU, 0.10)
    assert np.isclose(w @ SIGMA @ w, frontier_variance(MU, SIGMA, 0.10))


def test_numerical_solver_matches_closed_form_when_shorts_are_allowed():
    for target in [0.02, 0.06, 0.10, 0.15]:
        w_closed = efficient_weights(MU, SIGMA, target)
        w_numerical = minimize_variance(MU, SIGMA, target, allow_short=True)
        assert np.allclose(w_closed, w_numerical, atol=1e-5)


def test_no_short_weights_are_nonnegative():
    # A 11.5% target mean requires shorting asset 1 when shorts are allowed.
    assert efficient_weights(MU, SIGMA, 0.115).min() < 0
    w = minimize_variance(MU, SIGMA, 0.115, allow_short=False)
    assert w.min() >= -1e-9
    assert np.isclose(w.sum(), 1)
    assert np.isclose(w @ MU, 0.115)


def test_a_constraint_can_only_raise_the_minimum_variance():
    targets = np.linspace(MU.min(), MU.max(), 15)
    unconstrained = frontier(MU, SIGMA, targets, allow_short=True)
    constrained = frontier(MU, SIGMA, targets, allow_short=False)
    for w_u, w_c in zip(unconstrained, constrained):
        assert w_c @ SIGMA @ w_c >= w_u @ SIGMA @ w_u - 1e-10


def test_max_sharpe_matches_the_tangency_formula():
    w_formula = np.linalg.solve(SIGMA, MU - RF)
    w_formula = w_formula / w_formula.sum()
    w_numerical = max_sharpe_weights(MU, SIGMA, RF, allow_short=True)
    assert np.allclose(w_formula, w_numerical, atol=1e-5)
