from github_skills import (
    I_HAVE_COMPLETED_INTRODUCTION_TO_GITHUB,
    URL_TO_MY_COMPLETED_INTRODUCTION_TO_GITHUB_REPO,
    I_HAVE_COMPLETED_COMMUNICATE_USING_MARKDOWN,
    URL_TO_MY_COMPLETED_COMMUNICATE_USING_MARKDOWN_REPO,
    I_HAVE_COMPLETED_GITHUB_PAGES,
    URL_TO_MY_COMPLETED_GITHUB_PAGES_REPO,
)


def test_introduction_to_github():
    assert I_HAVE_COMPLETED_INTRODUCTION_TO_GITHUB
    assert URL_TO_MY_COMPLETED_INTRODUCTION_TO_GITHUB_REPO != ""


def test_communicate_using_markdown():
    assert I_HAVE_COMPLETED_COMMUNICATE_USING_MARKDOWN
    assert URL_TO_MY_COMPLETED_COMMUNICATE_USING_MARKDOWN_REPO != ""


def test_github_pages():
    assert I_HAVE_COMPLETED_GITHUB_PAGES
    assert URL_TO_MY_COMPLETED_GITHUB_PAGES_REPO != ""

