"""Tests for port_opt.py. Do not edit this file.

These tests use small, made-up inputs with known answers, so they run anywhere
(including on GitHub Actions) without needing any data files.
"""

import numpy as np

from port_opt import (
    find_global_minimum_variance_portfolio,
    find_tangency_portfolio,
    portfolio_mean,
    portfolio_variance,
)

MU = np.array([0.04, 0.08, 0.12])
SIGMA = np.array(
    [
        [0.04, 0.01, 0.00],
        [0.01, 0.09, 0.02],
        [0.00, 0.02, 0.16],
    ]
)
RF = 0.02


def sharpe_ratio(w, mu=MU, Sigma=SIGMA, rf=RF):
    return (portfolio_mean(w, mu) - rf) / np.sqrt(portfolio_variance(w, Sigma))


def random_portfolios(n_portfolios=500, n_assets=3, seed=0):
    rng = np.random.default_rng(seed)
    w = rng.normal(size=(n_portfolios, n_assets))
    w = w[np.abs(w.sum(axis=1)) > 0.1]  # avoid dividing by a sum near zero
    return w / w.sum(axis=1, keepdims=True)


def test_gmv_with_uncorrelated_assets():
    # With uncorrelated assets, each weight is proportional to 1 / variance.
    Sigma = np.diag([0.01, 0.04])
    wstar = find_global_minimum_variance_portfolio(Sigma)
    assert np.allclose(wstar, [0.8, 0.2], atol=1e-4)


def test_gmv_known_answer():
    wstar = find_global_minimum_variance_portfolio(SIGMA)
    assert np.isclose(wstar.sum(), 1)
    assert np.allclose(wstar, [0.6462, 0.2051, 0.1487], atol=1e-3)


def test_gmv_beats_random_portfolios():
    wstar = find_global_minimum_variance_portfolio(SIGMA)
    var_star = portfolio_variance(wstar, SIGMA)
    for w in random_portfolios():
        assert var_star <= portfolio_variance(w, SIGMA) + 1e-10


def test_tangency_known_answer():
    wstar = find_tangency_portfolio(MU, SIGMA, RF)
    assert np.isclose(wstar.sum(), 1)
    assert np.allclose(wstar, [0.2609, 0.3478, 0.3913], atol=1e-3)


def test_tangency_beats_random_portfolios():
    wstar = find_tangency_portfolio(MU, SIGMA, RF)
    sharpe_star = sharpe_ratio(wstar)
    for w in random_portfolios():
        assert sharpe_star >= sharpe_ratio(w) - 1e-10
